version: '3'

services:


  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    ############### REMOVE: production ######################### 
    volumes:
      - ./cmd/gateway:/app/cmd/gateway
    ############### REMOVE: production ######################### 
    ports:
      - "8080:8080"
    depends_on:
      gateway_db:
        condition: service_healthy
      alice:
        condition: service_started
      bob:
        condition: service_started
    ############### CHANGE: production ######################### 
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=requestlog
    ############### CHANGE: production ######################### 
  
  alice:
    build:
      context: .
      dockerfile: cmd/alice/Dockerfile
    ############### REMOVE: production ######################### 
    volumes:
      - ./cmd/alice:/app/cmd/alice
    ############### REMOVE: production ######################### 
    expose:
      - "50052"
    depends_on:
      alice_db:
        condition: service_healthy
    environment:
      - DB_HOST=alice_db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=alice
      - SERVER_PORT=50052

  bob:
    build:
      context: .
      dockerfile: cmd/bob/Dockerfile
    ############### REMOVE: production ######################### 
    volumes:
      - ./cmd/bob:/app/cmd/bob
    ############### REMOVE: production ######################### 
    expose:
      - "50051"
    depends_on:
      bob_db:
        condition: service_healthy
    environment:
      - DB_HOST=bob_db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=bob
      - SERVER_PORT=50051

  gateway_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gateway
    volumes:
      - ./cmd/gateway/data:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=password']
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"


  alice_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: alice
    volumes:
      - ./cmd/alice/data:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=password']
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"

  bob_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bob
    volumes:
      - ./cmd/bob/data:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=password']
      timeout: 20s
      retries: 10
    ports:
      - "3308:3306"
  