// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: pkg/api/grpc/dkg/dkg.proto

package dkg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DKG_ProcessDKG_FullMethodName = "/dkg.DKG/ProcessDKG"
)

// DKGClient is the client API for DKG service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DKGClient interface {
	ProcessDKG(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (*NumberResponse, error)
}

type dKGClient struct {
	cc grpc.ClientConnInterface
}

func NewDKGClient(cc grpc.ClientConnInterface) DKGClient {
	return &dKGClient{cc}
}

func (c *dKGClient) ProcessDKG(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (*NumberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NumberResponse)
	err := c.cc.Invoke(ctx, DKG_ProcessDKG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DKGServer is the server API for DKG service.
// All implementations must embed UnimplementedDKGServer
// for forward compatibility
type DKGServer interface {
	ProcessDKG(context.Context, *NumberRequest) (*NumberResponse, error)
	mustEmbedUnimplementedDKGServer()
}

// UnimplementedDKGServer must be embedded to have forward compatible implementations.
type UnimplementedDKGServer struct {
}

func (UnimplementedDKGServer) ProcessDKG(context.Context, *NumberRequest) (*NumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessDKG not implemented")
}
func (UnimplementedDKGServer) mustEmbedUnimplementedDKGServer() {}

// UnsafeDKGServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DKGServer will
// result in compilation errors.
type UnsafeDKGServer interface {
	mustEmbedUnimplementedDKGServer()
}

func RegisterDKGServer(s grpc.ServiceRegistrar, srv DKGServer) {
	s.RegisterService(&DKG_ServiceDesc, srv)
}

func _DKG_ProcessDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKGServer).ProcessDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DKG_ProcessDKG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKGServer).ProcessDKG(ctx, req.(*NumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DKG_ServiceDesc is the grpc.ServiceDesc for DKG service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DKG_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dkg.DKG",
	HandlerType: (*DKGServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessDKG",
			Handler:    _DKG_ProcessDKG_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/grpc/dkg/dkg.proto",
}
