// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: pkg/api/grpc/sign/sign.proto

package sign

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*SignMessage_Round1Request
	//	*SignMessage_Round1Response
	//	*SignMessage_Round2Request
	//	*SignMessage_Round2Response
	//	*SignMessage_Round3Request
	//	*SignMessage_Round3Response
	//	*SignMessage_Round4Request
	//	*SignMessage_Round4Response
	//	*SignMessage_SignResponse
	Msg isSignMessage_Msg `protobuf_oneof:"msg"`
}

func (x *SignMessage) Reset() {
	*x = SignMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessage) ProtoMessage() {}

func (x *SignMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessage.ProtoReflect.Descriptor instead.
func (*SignMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{0}
}

func (m *SignMessage) GetMsg() isSignMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *SignMessage) GetRound1Request() *Round1Request {
	if x, ok := x.GetMsg().(*SignMessage_Round1Request); ok {
		return x.Round1Request
	}
	return nil
}

func (x *SignMessage) GetRound1Response() *Round1Response {
	if x, ok := x.GetMsg().(*SignMessage_Round1Response); ok {
		return x.Round1Response
	}
	return nil
}

func (x *SignMessage) GetRound2Request() *Round2Request {
	if x, ok := x.GetMsg().(*SignMessage_Round2Request); ok {
		return x.Round2Request
	}
	return nil
}

func (x *SignMessage) GetRound2Response() *Round2Response {
	if x, ok := x.GetMsg().(*SignMessage_Round2Response); ok {
		return x.Round2Response
	}
	return nil
}

func (x *SignMessage) GetRound3Request() *Round3Request {
	if x, ok := x.GetMsg().(*SignMessage_Round3Request); ok {
		return x.Round3Request
	}
	return nil
}

func (x *SignMessage) GetRound3Response() *Round3Response {
	if x, ok := x.GetMsg().(*SignMessage_Round3Response); ok {
		return x.Round3Response
	}
	return nil
}

func (x *SignMessage) GetRound4Request() *Round4Request {
	if x, ok := x.GetMsg().(*SignMessage_Round4Request); ok {
		return x.Round4Request
	}
	return nil
}

func (x *SignMessage) GetRound4Response() *Round4Response {
	if x, ok := x.GetMsg().(*SignMessage_Round4Response); ok {
		return x.Round4Response
	}
	return nil
}

func (x *SignMessage) GetSignResponse() *SignResponse {
	if x, ok := x.GetMsg().(*SignMessage_SignResponse); ok {
		return x.SignResponse
	}
	return nil
}

type isSignMessage_Msg interface {
	isSignMessage_Msg()
}

type SignMessage_Round1Request struct {
	Round1Request *Round1Request `protobuf:"bytes,1,opt,name=round1Request,proto3,oneof"`
}

type SignMessage_Round1Response struct {
	Round1Response *Round1Response `protobuf:"bytes,2,opt,name=round1Response,proto3,oneof"`
}

type SignMessage_Round2Request struct {
	Round2Request *Round2Request `protobuf:"bytes,3,opt,name=round2Request,proto3,oneof"`
}

type SignMessage_Round2Response struct {
	Round2Response *Round2Response `protobuf:"bytes,4,opt,name=round2Response,proto3,oneof"`
}

type SignMessage_Round3Request struct {
	Round3Request *Round3Request `protobuf:"bytes,5,opt,name=round3Request,proto3,oneof"`
}

type SignMessage_Round3Response struct {
	Round3Response *Round3Response `protobuf:"bytes,6,opt,name=round3Response,proto3,oneof"`
}

type SignMessage_Round4Request struct {
	Round4Request *Round4Request `protobuf:"bytes,7,opt,name=round4Request,proto3,oneof"`
}

type SignMessage_Round4Response struct {
	Round4Response *Round4Response `protobuf:"bytes,8,opt,name=round4Response,proto3,oneof"`
}

type SignMessage_SignResponse struct {
	SignResponse *SignResponse `protobuf:"bytes,21,opt,name=signResponse,proto3,oneof"`
}

func (*SignMessage_Round1Request) isSignMessage_Msg() {}

func (*SignMessage_Round1Response) isSignMessage_Msg() {}

func (*SignMessage_Round2Request) isSignMessage_Msg() {}

func (*SignMessage_Round2Response) isSignMessage_Msg() {}

func (*SignMessage_Round3Request) isSignMessage_Msg() {}

func (*SignMessage_Round3Response) isSignMessage_Msg() {}

func (*SignMessage_Round4Request) isSignMessage_Msg() {}

func (*SignMessage_Round4Response) isSignMessage_Msg() {}

func (*SignMessage_SignResponse) isSignMessage_Msg() {}

type Round1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Round1Request) Reset() {
	*x = Round1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round1Request) ProtoMessage() {}

func (x *Round1Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round1Request.ProtoReflect.Descriptor instead.
func (*Round1Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{1}
}

type Round1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed []byte `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *Round1Response) Reset() {
	*x = Round1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round1Response) ProtoMessage() {}

func (x *Round1Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round1Response.ProtoReflect.Descriptor instead.
func (*Round1Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{2}
}

func (x *Round1Response) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type Round2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed []byte `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *Round2Request) Reset() {
	*x = Round2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round2Request) ProtoMessage() {}

func (x *Round2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round2Request.ProtoReflect.Descriptor instead.
func (*Round2Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{3}
}

func (x *Round2Request) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type Round2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output *SignRound2Output `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *Round2Response) Reset() {
	*x = Round2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round2Response) ProtoMessage() {}

func (x *Round2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round2Response.ProtoReflect.Descriptor instead.
func (*Round2Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{4}
}

func (x *Round2Response) GetOutput() *SignRound2Output {
	if x != nil {
		return x.Output
	}
	return nil
}

type Round3Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round2Output *SignRound2Output `protobuf:"bytes,1,opt,name=round2_output,json=round2Output,proto3" json:"round2_output,omitempty"`
	Message      []byte            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Round3Request) Reset() {
	*x = Round3Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round3Request) ProtoMessage() {}

func (x *Round3Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round3Request.ProtoReflect.Descriptor instead.
func (*Round3Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{5}
}

func (x *Round3Request) GetRound2Output() *SignRound2Output {
	if x != nil {
		return x.Round2Output
	}
	return nil
}

func (x *Round3Request) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type Round3Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output *SignRound3Output `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *Round3Response) Reset() {
	*x = Round3Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round3Response) ProtoMessage() {}

func (x *Round3Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round3Response.ProtoReflect.Descriptor instead.
func (*Round3Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{6}
}

func (x *Round3Response) GetOutput() *SignRound3Output {
	if x != nil {
		return x.Output
	}
	return nil
}

type Round4Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round3Output *SignRound3Output `protobuf:"bytes,1,opt,name=round3_output,json=round3Output,proto3" json:"round3_output,omitempty"`
	Message      []byte            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Round4Request) Reset() {
	*x = Round4Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round4Request) ProtoMessage() {}

func (x *Round4Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round4Request.ProtoReflect.Descriptor instead.
func (*Round4Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{7}
}

func (x *Round4Request) GetRound3Output() *SignRound3Output {
	if x != nil {
		return x.Round3Output
	}
	return nil
}

func (x *Round4Request) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type Round4Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Round4Response) Reset() {
	*x = Round4Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round4Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round4Response) ProtoMessage() {}

func (x *Round4Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round4Response.ProtoReflect.Descriptor instead.
func (*Round4Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{8}
}

type SignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature *EcdsaSignature `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{9}
}

func (x *SignResponse) GetSignature() *EcdsaSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SignRound2Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KosRound1Outputs []*KosRound1Output `protobuf:"bytes,1,rep,name=kos_round1_outputs,json=kosRound1Outputs,proto3" json:"kos_round1_outputs,omitempty"`
	Db               []byte             `protobuf:"bytes,2,opt,name=db,proto3" json:"db,omitempty"`
	Seed             []byte             `protobuf:"bytes,3,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *SignRound2Output) Reset() {
	*x = SignRound2Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignRound2Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRound2Output) ProtoMessage() {}

func (x *SignRound2Output) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRound2Output.ProtoReflect.Descriptor instead.
func (*SignRound2Output) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{10}
}

func (x *SignRound2Output) GetKosRound1Outputs() []*KosRound1Output {
	if x != nil {
		return x.KosRound1Outputs
	}
	return nil
}

func (x *SignRound2Output) GetDb() []byte {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *SignRound2Output) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type SignRound3Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MultiplyRound2Outputs []*MultiplyRound2Output `protobuf:"bytes,1,rep,name=multiply_round2_outputs,json=multiplyRound2Outputs,proto3" json:"multiply_round2_outputs,omitempty"`
	RSchnorrProof         *SchnorrProof           `protobuf:"bytes,2,opt,name=r_schnorr_proof,json=rSchnorrProof,proto3" json:"r_schnorr_proof,omitempty"`
	RPrime                []byte                  `protobuf:"bytes,3,opt,name=r_prime,json=rPrime,proto3" json:"r_prime,omitempty"`
	EtaPhi                []byte                  `protobuf:"bytes,4,opt,name=eta_phi,json=etaPhi,proto3" json:"eta_phi,omitempty"`
	EtaSig                []byte                  `protobuf:"bytes,5,opt,name=eta_sig,json=etaSig,proto3" json:"eta_sig,omitempty"`
}

func (x *SignRound3Output) Reset() {
	*x = SignRound3Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignRound3Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRound3Output) ProtoMessage() {}

func (x *SignRound3Output) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRound3Output.ProtoReflect.Descriptor instead.
func (*SignRound3Output) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{11}
}

func (x *SignRound3Output) GetMultiplyRound2Outputs() []*MultiplyRound2Output {
	if x != nil {
		return x.MultiplyRound2Outputs
	}
	return nil
}

func (x *SignRound3Output) GetRSchnorrProof() *SchnorrProof {
	if x != nil {
		return x.RSchnorrProof
	}
	return nil
}

func (x *SignRound3Output) GetRPrime() []byte {
	if x != nil {
		return x.RPrime
	}
	return nil
}

func (x *SignRound3Output) GetEtaPhi() []byte {
	if x != nil {
		return x.EtaPhi
	}
	return nil
}

func (x *SignRound3Output) GetEtaSig() []byte {
	if x != nil {
		return x.EtaSig
	}
	return nil
}

type KosRound1Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	U      [][]byte `protobuf:"bytes,1,rep,name=u,proto3" json:"u,omitempty"`
	WPrime []byte   `protobuf:"bytes,2,opt,name=w_prime,json=wPrime,proto3" json:"w_prime,omitempty"`
	VPrime []byte   `protobuf:"bytes,3,opt,name=v_prime,json=vPrime,proto3" json:"v_prime,omitempty"`
}

func (x *KosRound1Output) Reset() {
	*x = KosRound1Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KosRound1Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KosRound1Output) ProtoMessage() {}

func (x *KosRound1Output) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KosRound1Output.ProtoReflect.Descriptor instead.
func (*KosRound1Output) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{12}
}

func (x *KosRound1Output) GetU() [][]byte {
	if x != nil {
		return x.U
	}
	return nil
}

func (x *KosRound1Output) GetWPrime() []byte {
	if x != nil {
		return x.WPrime
	}
	return nil
}

func (x *KosRound1Output) GetVPrime() []byte {
	if x != nil {
		return x.VPrime
	}
	return nil
}

type MultiplyRound2Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CotRound2Output *COTRound2Output `protobuf:"bytes,1,opt,name=cot_round2_output,json=cotRound2Output,proto3" json:"cot_round2_output,omitempty"`
	R               [][]byte         `protobuf:"bytes,2,rep,name=r,proto3" json:"r,omitempty"`
	U               []byte           `protobuf:"bytes,3,opt,name=u,proto3" json:"u,omitempty"`
}

func (x *MultiplyRound2Output) Reset() {
	*x = MultiplyRound2Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiplyRound2Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplyRound2Output) ProtoMessage() {}

func (x *MultiplyRound2Output) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplyRound2Output.ProtoReflect.Descriptor instead.
func (*MultiplyRound2Output) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{13}
}

func (x *MultiplyRound2Output) GetCotRound2Output() *COTRound2Output {
	if x != nil {
		return x.CotRound2Output
	}
	return nil
}

func (x *MultiplyRound2Output) GetR() [][]byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *MultiplyRound2Output) GetU() []byte {
	if x != nil {
		return x.U
	}
	return nil
}

type COTRound2Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tau [][]byte `protobuf:"bytes,1,rep,name=tau,proto3" json:"tau,omitempty"`
}

func (x *COTRound2Output) Reset() {
	*x = COTRound2Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *COTRound2Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*COTRound2Output) ProtoMessage() {}

func (x *COTRound2Output) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use COTRound2Output.ProtoReflect.Descriptor instead.
func (*COTRound2Output) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{14}
}

func (x *COTRound2Output) GetTau() [][]byte {
	if x != nil {
		return x.Tau
	}
	return nil
}

type SchnorrProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statement  []byte `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
	Commitment []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	Challenge  []byte `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Response   []byte `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *SchnorrProof) Reset() {
	*x = SchnorrProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchnorrProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchnorrProof) ProtoMessage() {}

func (x *SchnorrProof) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchnorrProof.ProtoReflect.Descriptor instead.
func (*SchnorrProof) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{15}
}

func (x *SchnorrProof) GetStatement() []byte {
	if x != nil {
		return x.Statement
	}
	return nil
}

func (x *SchnorrProof) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *SchnorrProof) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *SchnorrProof) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type EcdsaSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R []byte `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	V int32  `protobuf:"varint,3,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *EcdsaSignature) Reset() {
	*x = EcdsaSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EcdsaSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcdsaSignature) ProtoMessage() {}

func (x *EcdsaSignature) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_sign_sign_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcdsaSignature.ProtoReflect.Descriptor instead.
func (*EcdsaSignature) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_sign_sign_proto_rawDescGZIP(), []int{16}
}

func (x *EcdsaSignature) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *EcdsaSignature) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *EcdsaSignature) GetV() int32 {
	if x != nil {
		return x.V
	}
	return 0
}

var File_pkg_api_grpc_sign_sign_proto protoreflect.FileDescriptor

var file_pkg_api_grpc_sign_sign_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73,
	0x69, 0x67, 0x6e, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x73, 0x69, 0x67, 0x6e, 0x22, 0xc2, 0x04, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x69,
	0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x69, 0x67, 0x6e,
	0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e,
	0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x33, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x73, 0x69, 0x67, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0e, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64,
	0x22, 0x23, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x73, 0x65, 0x65, 0x64, 0x22, 0x40, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x66, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x32, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x0c, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x40, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x33, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x22, 0x66, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x5f, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x69, 0x67, 0x6e,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x52, 0x0c, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x42, 0x0a, 0x0c, 0x53,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x45, 0x63, 0x64, 0x73, 0x61, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0x7b, 0x0a, 0x10, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x43, 0x0a, 0x12, 0x6b, 0x6f, 0x73, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x31, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x4b, 0x6f, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x10, 0x6b, 0x6f, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x31, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x64, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x22, 0xed, 0x01, 0x0a,
	0x10, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x52, 0x0a, 0x17, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x5f, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x32, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x79, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x15,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x3a, 0x0a, 0x0f, 0x72, 0x5f, 0x73, 0x63, 0x68, 0x6e, 0x6f,
	0x72, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x53, 0x63, 0x68, 0x6e, 0x6f, 0x72, 0x72, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x52, 0x0d, 0x72, 0x53, 0x63, 0x68, 0x6e, 0x6f, 0x72, 0x72, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x5f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x72, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x74,
	0x61, 0x5f, 0x70, 0x68, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x74, 0x61,
	0x50, 0x68, 0x69, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x69, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x74, 0x61, 0x53, 0x69, 0x67, 0x22, 0x51, 0x0a, 0x0f,
	0x4b, 0x6f, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x0c, 0x0a, 0x01, 0x75, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x01, 0x75, 0x12, 0x17, 0x0a,
	0x07, 0x77, 0x5f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x77, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x5f, 0x70, 0x72, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x22,
	0x75, 0x0a, 0x14, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x41, 0x0a, 0x11, 0x63, 0x6f, 0x74, 0x5f, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x32, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x43, 0x4f, 0x54, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x0f, 0x63, 0x6f, 0x74, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x75, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x01, 0x75, 0x22, 0x23, 0x0a, 0x0f, 0x43, 0x4f, 0x54, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x75,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03, 0x74, 0x61, 0x75, 0x22, 0x86, 0x01, 0x0a, 0x0c,
	0x53, 0x63, 0x68, 0x6e, 0x6f, 0x72, 0x72, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3a, 0x0a, 0x0e, 0x45, 0x63, 0x64, 0x73, 0x61, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x01, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x76,
	0x32, 0x3f, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x30, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x11, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x11, 0x2e, 0x73, 0x69, 0x67,
	0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_grpc_sign_sign_proto_rawDescOnce sync.Once
	file_pkg_api_grpc_sign_sign_proto_rawDescData = file_pkg_api_grpc_sign_sign_proto_rawDesc
)

func file_pkg_api_grpc_sign_sign_proto_rawDescGZIP() []byte {
	file_pkg_api_grpc_sign_sign_proto_rawDescOnce.Do(func() {
		file_pkg_api_grpc_sign_sign_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_grpc_sign_sign_proto_rawDescData)
	})
	return file_pkg_api_grpc_sign_sign_proto_rawDescData
}

var file_pkg_api_grpc_sign_sign_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_api_grpc_sign_sign_proto_goTypes = []any{
	(*SignMessage)(nil),          // 0: sign.SignMessage
	(*Round1Request)(nil),        // 1: sign.Round1Request
	(*Round1Response)(nil),       // 2: sign.Round1Response
	(*Round2Request)(nil),        // 3: sign.Round2Request
	(*Round2Response)(nil),       // 4: sign.Round2Response
	(*Round3Request)(nil),        // 5: sign.Round3Request
	(*Round3Response)(nil),       // 6: sign.Round3Response
	(*Round4Request)(nil),        // 7: sign.Round4Request
	(*Round4Response)(nil),       // 8: sign.Round4Response
	(*SignResponse)(nil),         // 9: sign.SignResponse
	(*SignRound2Output)(nil),     // 10: sign.SignRound2Output
	(*SignRound3Output)(nil),     // 11: sign.SignRound3Output
	(*KosRound1Output)(nil),      // 12: sign.KosRound1Output
	(*MultiplyRound2Output)(nil), // 13: sign.MultiplyRound2Output
	(*COTRound2Output)(nil),      // 14: sign.COTRound2Output
	(*SchnorrProof)(nil),         // 15: sign.SchnorrProof
	(*EcdsaSignature)(nil),       // 16: sign.EcdsaSignature
}
var file_pkg_api_grpc_sign_sign_proto_depIdxs = []int32{
	1,  // 0: sign.SignMessage.round1Request:type_name -> sign.Round1Request
	2,  // 1: sign.SignMessage.round1Response:type_name -> sign.Round1Response
	3,  // 2: sign.SignMessage.round2Request:type_name -> sign.Round2Request
	4,  // 3: sign.SignMessage.round2Response:type_name -> sign.Round2Response
	5,  // 4: sign.SignMessage.round3Request:type_name -> sign.Round3Request
	6,  // 5: sign.SignMessage.round3Response:type_name -> sign.Round3Response
	7,  // 6: sign.SignMessage.round4Request:type_name -> sign.Round4Request
	8,  // 7: sign.SignMessage.round4Response:type_name -> sign.Round4Response
	9,  // 8: sign.SignMessage.signResponse:type_name -> sign.SignResponse
	10, // 9: sign.Round2Response.output:type_name -> sign.SignRound2Output
	10, // 10: sign.Round3Request.round2_output:type_name -> sign.SignRound2Output
	11, // 11: sign.Round3Response.output:type_name -> sign.SignRound3Output
	11, // 12: sign.Round4Request.round3_output:type_name -> sign.SignRound3Output
	16, // 13: sign.SignResponse.signature:type_name -> sign.EcdsaSignature
	12, // 14: sign.SignRound2Output.kos_round1_outputs:type_name -> sign.KosRound1Output
	13, // 15: sign.SignRound3Output.multiply_round2_outputs:type_name -> sign.MultiplyRound2Output
	15, // 16: sign.SignRound3Output.r_schnorr_proof:type_name -> sign.SchnorrProof
	14, // 17: sign.MultiplyRound2Output.cot_round2_output:type_name -> sign.COTRound2Output
	0,  // 18: sign.SignService.Sign:input_type -> sign.SignMessage
	0,  // 19: sign.SignService.Sign:output_type -> sign.SignMessage
	19, // [19:20] is the sub-list for method output_type
	18, // [18:19] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_api_grpc_sign_sign_proto_init() }
func file_pkg_api_grpc_sign_sign_proto_init() {
	if File_pkg_api_grpc_sign_sign_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_grpc_sign_sign_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SignMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Round1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Round1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Round2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Round2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Round3Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Round3Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Round4Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Round4Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SignRound2Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SignRound3Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*KosRound1Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*MultiplyRound2Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*COTRound2Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*SchnorrProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_grpc_sign_sign_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*EcdsaSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_api_grpc_sign_sign_proto_msgTypes[0].OneofWrappers = []any{
		(*SignMessage_Round1Request)(nil),
		(*SignMessage_Round1Response)(nil),
		(*SignMessage_Round2Request)(nil),
		(*SignMessage_Round2Response)(nil),
		(*SignMessage_Round3Request)(nil),
		(*SignMessage_Round3Response)(nil),
		(*SignMessage_Round4Request)(nil),
		(*SignMessage_Round4Response)(nil),
		(*SignMessage_SignResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_grpc_sign_sign_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_grpc_sign_sign_proto_goTypes,
		DependencyIndexes: file_pkg_api_grpc_sign_sign_proto_depIdxs,
		MessageInfos:      file_pkg_api_grpc_sign_sign_proto_msgTypes,
	}.Build()
	File_pkg_api_grpc_sign_sign_proto = out.File
	file_pkg_api_grpc_sign_sign_proto_rawDesc = nil
	file_pkg_api_grpc_sign_sign_proto_goTypes = nil
	file_pkg_api_grpc_sign_sign_proto_depIdxs = nil
}
