// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: sign/sign.proto

package sign

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*SignMessage_SignRequest
	//	*SignMessage_Round1Request
	//	*SignMessage_Round1Response
	//	*SignMessage_Round2Request
	//	*SignMessage_Round2Response
	//	*SignMessage_Round3Request
	//	*SignMessage_Round3Response
	//	*SignMessage_Round4Request
	//	*SignMessage_Round4Response
	//	*SignMessage_SignResponse
	Msg isSignMessage_Msg `protobuf_oneof:"msg"`
}

func (x *SignMessage) Reset() {
	*x = SignMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessage) ProtoMessage() {}

func (x *SignMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessage.ProtoReflect.Descriptor instead.
func (*SignMessage) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{0}
}

func (m *SignMessage) GetMsg() isSignMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *SignMessage) GetSignRequest() *SignRequest {
	if x, ok := x.GetMsg().(*SignMessage_SignRequest); ok {
		return x.SignRequest
	}
	return nil
}

func (x *SignMessage) GetRound1Request() *Round1Request {
	if x, ok := x.GetMsg().(*SignMessage_Round1Request); ok {
		return x.Round1Request
	}
	return nil
}

func (x *SignMessage) GetRound1Response() *Round1Response {
	if x, ok := x.GetMsg().(*SignMessage_Round1Response); ok {
		return x.Round1Response
	}
	return nil
}

func (x *SignMessage) GetRound2Request() *Round2Request {
	if x, ok := x.GetMsg().(*SignMessage_Round2Request); ok {
		return x.Round2Request
	}
	return nil
}

func (x *SignMessage) GetRound2Response() *Round2Response {
	if x, ok := x.GetMsg().(*SignMessage_Round2Response); ok {
		return x.Round2Response
	}
	return nil
}

func (x *SignMessage) GetRound3Request() *Round3Request {
	if x, ok := x.GetMsg().(*SignMessage_Round3Request); ok {
		return x.Round3Request
	}
	return nil
}

func (x *SignMessage) GetRound3Response() *Round3Response {
	if x, ok := x.GetMsg().(*SignMessage_Round3Response); ok {
		return x.Round3Response
	}
	return nil
}

func (x *SignMessage) GetRound4Request() *Round4Request {
	if x, ok := x.GetMsg().(*SignMessage_Round4Request); ok {
		return x.Round4Request
	}
	return nil
}

func (x *SignMessage) GetRound4Response() *Round4Response {
	if x, ok := x.GetMsg().(*SignMessage_Round4Response); ok {
		return x.Round4Response
	}
	return nil
}

func (x *SignMessage) GetSignResponse() *SignResponse {
	if x, ok := x.GetMsg().(*SignMessage_SignResponse); ok {
		return x.SignResponse
	}
	return nil
}

type isSignMessage_Msg interface {
	isSignMessage_Msg()
}

type SignMessage_SignRequest struct {
	SignRequest *SignRequest `protobuf:"bytes,1,opt,name=signRequest,proto3,oneof"`
}

type SignMessage_Round1Request struct {
	Round1Request *Round1Request `protobuf:"bytes,2,opt,name=round1Request,proto3,oneof"`
}

type SignMessage_Round1Response struct {
	Round1Response *Round1Response `protobuf:"bytes,3,opt,name=round1Response,proto3,oneof"`
}

type SignMessage_Round2Request struct {
	Round2Request *Round2Request `protobuf:"bytes,4,opt,name=round2Request,proto3,oneof"`
}

type SignMessage_Round2Response struct {
	Round2Response *Round2Response `protobuf:"bytes,5,opt,name=round2Response,proto3,oneof"`
}

type SignMessage_Round3Request struct {
	Round3Request *Round3Request `protobuf:"bytes,6,opt,name=round3Request,proto3,oneof"`
}

type SignMessage_Round3Response struct {
	Round3Response *Round3Response `protobuf:"bytes,7,opt,name=round3Response,proto3,oneof"`
}

type SignMessage_Round4Request struct {
	Round4Request *Round4Request `protobuf:"bytes,8,opt,name=round4Request,proto3,oneof"`
}

type SignMessage_Round4Response struct {
	Round4Response *Round4Response `protobuf:"bytes,9,opt,name=round4Response,proto3,oneof"`
}

type SignMessage_SignResponse struct {
	SignResponse *SignResponse `protobuf:"bytes,10,opt,name=signResponse,proto3,oneof"`
}

func (*SignMessage_SignRequest) isSignMessage_Msg() {}

func (*SignMessage_Round1Request) isSignMessage_Msg() {}

func (*SignMessage_Round1Response) isSignMessage_Msg() {}

func (*SignMessage_Round2Request) isSignMessage_Msg() {}

func (*SignMessage_Round2Response) isSignMessage_Msg() {}

func (*SignMessage_Round3Request) isSignMessage_Msg() {}

func (*SignMessage_Round3Response) isSignMessage_Msg() {}

func (*SignMessage_Round4Request) isSignMessage_Msg() {}

func (*SignMessage_Round4Response) isSignMessage_Msg() {}

func (*SignMessage_SignResponse) isSignMessage_Msg() {}

type SignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	SecretKey []byte `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Message   []byte `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{1}
}

func (x *SignRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SignRequest) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

func (x *SignRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type Round1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Round1Request) Reset() {
	*x = Round1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round1Request) ProtoMessage() {}

func (x *Round1Request) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round1Request.ProtoReflect.Descriptor instead.
func (*Round1Request) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{2}
}

func (x *Round1Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Round1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Round1Response) Reset() {
	*x = Round1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round1Response) ProtoMessage() {}

func (x *Round1Response) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round1Response.ProtoReflect.Descriptor instead.
func (*Round1Response) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{3}
}

func (x *Round1Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Round2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Round2Request) Reset() {
	*x = Round2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round2Request) ProtoMessage() {}

func (x *Round2Request) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round2Request.ProtoReflect.Descriptor instead.
func (*Round2Request) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{4}
}

func (x *Round2Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Round2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Round2Response) Reset() {
	*x = Round2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round2Response) ProtoMessage() {}

func (x *Round2Response) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round2Response.ProtoReflect.Descriptor instead.
func (*Round2Response) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{5}
}

func (x *Round2Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Round3Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Round3Request) Reset() {
	*x = Round3Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round3Request) ProtoMessage() {}

func (x *Round3Request) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round3Request.ProtoReflect.Descriptor instead.
func (*Round3Request) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{6}
}

func (x *Round3Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Round3Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Round3Response) Reset() {
	*x = Round3Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round3Response) ProtoMessage() {}

func (x *Round3Response) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round3Response.ProtoReflect.Descriptor instead.
func (*Round3Response) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{7}
}

func (x *Round3Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Round4Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Round4Request) Reset() {
	*x = Round4Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round4Request) ProtoMessage() {}

func (x *Round4Request) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round4Request.ProtoReflect.Descriptor instead.
func (*Round4Request) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{8}
}

func (x *Round4Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Round4Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Round4Response) Reset() {
	*x = Round4Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round4Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round4Response) ProtoMessage() {}

func (x *Round4Response) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round4Response.ProtoReflect.Descriptor instead.
func (*Round4Response) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{9}
}

func (x *Round4Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_sign_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sign_sign_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_sign_sign_proto_rawDescGZIP(), []int{10}
}

func (x *SignResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_sign_sign_proto protoreflect.FileDescriptor

var file_sign_sign_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0xf9, 0x04, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73,
	0x69, 0x67, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b,
	0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x73, 0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73,
	0x69, 0x67, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x69, 0x67,
	0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c,
	0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x05, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x60, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x29, 0x0a, 0x0d,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2a,
	0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x3f, 0x0a, 0x0b, 0x53,
	0x69, 0x67, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x53, 0x69,
	0x67, 0x6e, 0x12, 0x11, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x11, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11,
	0x74, 0x65, 0x63, 0x64, 0x73, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x69, 0x67,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sign_sign_proto_rawDescOnce sync.Once
	file_sign_sign_proto_rawDescData = file_sign_sign_proto_rawDesc
)

func file_sign_sign_proto_rawDescGZIP() []byte {
	file_sign_sign_proto_rawDescOnce.Do(func() {
		file_sign_sign_proto_rawDescData = protoimpl.X.CompressGZIP(file_sign_sign_proto_rawDescData)
	})
	return file_sign_sign_proto_rawDescData
}

var file_sign_sign_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sign_sign_proto_goTypes = []any{
	(*SignMessage)(nil),    // 0: sign.SignMessage
	(*SignRequest)(nil),    // 1: sign.SignRequest
	(*Round1Request)(nil),  // 2: sign.Round1Request
	(*Round1Response)(nil), // 3: sign.Round1Response
	(*Round2Request)(nil),  // 4: sign.Round2Request
	(*Round2Response)(nil), // 5: sign.Round2Response
	(*Round3Request)(nil),  // 6: sign.Round3Request
	(*Round3Response)(nil), // 7: sign.Round3Response
	(*Round4Request)(nil),  // 8: sign.Round4Request
	(*Round4Response)(nil), // 9: sign.Round4Response
	(*SignResponse)(nil),   // 10: sign.SignResponse
}
var file_sign_sign_proto_depIdxs = []int32{
	1,  // 0: sign.SignMessage.signRequest:type_name -> sign.SignRequest
	2,  // 1: sign.SignMessage.round1Request:type_name -> sign.Round1Request
	3,  // 2: sign.SignMessage.round1Response:type_name -> sign.Round1Response
	4,  // 3: sign.SignMessage.round2Request:type_name -> sign.Round2Request
	5,  // 4: sign.SignMessage.round2Response:type_name -> sign.Round2Response
	6,  // 5: sign.SignMessage.round3Request:type_name -> sign.Round3Request
	7,  // 6: sign.SignMessage.round3Response:type_name -> sign.Round3Response
	8,  // 7: sign.SignMessage.round4Request:type_name -> sign.Round4Request
	9,  // 8: sign.SignMessage.round4Response:type_name -> sign.Round4Response
	10, // 9: sign.SignMessage.signResponse:type_name -> sign.SignResponse
	0,  // 10: sign.SignService.Sign:input_type -> sign.SignMessage
	0,  // 11: sign.SignService.Sign:output_type -> sign.SignMessage
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sign_sign_proto_init() }
func file_sign_sign_proto_init() {
	if File_sign_sign_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sign_sign_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SignMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_sign_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_sign_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Round1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_sign_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Round1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_sign_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Round2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_sign_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Round2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_sign_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Round3Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_sign_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Round3Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_sign_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Round4Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_sign_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Round4Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_sign_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sign_sign_proto_msgTypes[0].OneofWrappers = []any{
		(*SignMessage_SignRequest)(nil),
		(*SignMessage_Round1Request)(nil),
		(*SignMessage_Round1Response)(nil),
		(*SignMessage_Round2Request)(nil),
		(*SignMessage_Round2Response)(nil),
		(*SignMessage_Round3Request)(nil),
		(*SignMessage_Round3Response)(nil),
		(*SignMessage_Round4Request)(nil),
		(*SignMessage_Round4Response)(nil),
		(*SignMessage_SignResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sign_sign_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sign_sign_proto_goTypes,
		DependencyIndexes: file_sign_sign_proto_depIdxs,
		MessageInfos:      file_sign_sign_proto_msgTypes,
	}.Build()
	File_sign_sign_proto = out.File
	file_sign_sign_proto_rawDesc = nil
	file_sign_sign_proto_goTypes = nil
	file_sign_sign_proto_depIdxs = nil
}
