
services:
  bitcoin:
    image: ruimarinho/bitcoin-core:latest
    command:
      -printtoconsole
      -regtest=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcauth=bitcoinrpc:73f6a6d2f6e78d5f9b8b8f8e7e8f8d8c$8c8f8e7d8f9b8b8f8e7e8f8d8c8f8e7d8f9b8b8f8e7e8f8d8c
    ports:
      - "18443:18443"
    volumes:
      - ./bitcoin-data:/home/bitcoin/.bitcoin