// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: keygen/keygen.proto

package keygen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	KeygenService_KeyGen_FullMethodName = "/keygen.KeygenService/KeyGen"
)

// KeygenServiceClient is the client API for KeygenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeygenServiceClient interface {
	KeyGen(ctx context.Context, opts ...grpc.CallOption) (KeygenService_KeyGenClient, error)
}

type keygenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeygenServiceClient(cc grpc.ClientConnInterface) KeygenServiceClient {
	return &keygenServiceClient{cc}
}

func (c *keygenServiceClient) KeyGen(ctx context.Context, opts ...grpc.CallOption) (KeygenService_KeyGenClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeygenService_ServiceDesc.Streams[0], KeygenService_KeyGen_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &keygenServiceKeyGenClient{ClientStream: stream}
	return x, nil
}

type KeygenService_KeyGenClient interface {
	Send(*KeygenMessage) error
	Recv() (*KeygenMessage, error)
	grpc.ClientStream
}

type keygenServiceKeyGenClient struct {
	grpc.ClientStream
}

func (x *keygenServiceKeyGenClient) Send(m *KeygenMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *keygenServiceKeyGenClient) Recv() (*KeygenMessage, error) {
	m := new(KeygenMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KeygenServiceServer is the server API for KeygenService service.
// All implementations must embed UnimplementedKeygenServiceServer
// for forward compatibility
type KeygenServiceServer interface {
	KeyGen(KeygenService_KeyGenServer) error
	mustEmbedUnimplementedKeygenServiceServer()
}

// UnimplementedKeygenServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKeygenServiceServer struct {
}

func (UnimplementedKeygenServiceServer) KeyGen(KeygenService_KeyGenServer) error {
	return status.Errorf(codes.Unimplemented, "method KeyGen not implemented")
}
func (UnimplementedKeygenServiceServer) mustEmbedUnimplementedKeygenServiceServer() {}

// UnsafeKeygenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeygenServiceServer will
// result in compilation errors.
type UnsafeKeygenServiceServer interface {
	mustEmbedUnimplementedKeygenServiceServer()
}

func RegisterKeygenServiceServer(s grpc.ServiceRegistrar, srv KeygenServiceServer) {
	s.RegisterService(&KeygenService_ServiceDesc, srv)
}

func _KeygenService_KeyGen_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeygenServiceServer).KeyGen(&keygenServiceKeyGenServer{ServerStream: stream})
}

type KeygenService_KeyGenServer interface {
	Send(*KeygenMessage) error
	Recv() (*KeygenMessage, error)
	grpc.ServerStream
}

type keygenServiceKeyGenServer struct {
	grpc.ServerStream
}

func (x *keygenServiceKeyGenServer) Send(m *KeygenMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *keygenServiceKeyGenServer) Recv() (*KeygenMessage, error) {
	m := new(KeygenMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KeygenService_ServiceDesc is the grpc.ServiceDesc for KeygenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeygenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keygen.KeygenService",
	HandlerType: (*KeygenServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KeyGen",
			Handler:       _KeygenService_KeyGen_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "keygen/keygen.proto",
}
