// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: keygen/keygen.proto

package keygen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeygenMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*KeygenMessage_KeyGenRequestTo1Output
	//	*KeygenMessage_KeyGenRound1To2Output
	//	*KeygenMessage_KeyGenRound2To3Output
	//	*KeygenMessage_KeyGenRound3To4Output
	//	*KeygenMessage_KeyGenRound4To5Output
	//	*KeygenMessage_KeyGenRound5To6Output
	//	*KeygenMessage_KeyGenRound6To7Output
	//	*KeygenMessage_KeyGenRound7To8Output
	//	*KeygenMessage_KeyGenRound8To9Output
	//	*KeygenMessage_KeyGenRound9To10Output
	//	*KeygenMessage_KeyGenRound10To11Output
	//	*KeygenMessage_KeyGenRound11ToResponseOutput
	Msg isKeygenMessage_Msg `protobuf_oneof:"msg"`
}

func (x *KeygenMessage) Reset() {
	*x = KeygenMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeygenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenMessage) ProtoMessage() {}

func (x *KeygenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenMessage.ProtoReflect.Descriptor instead.
func (*KeygenMessage) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{0}
}

func (m *KeygenMessage) GetMsg() isKeygenMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRequestTo1Output() *KeyGenRequestTo1Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRequestTo1Output); ok {
		return x.KeyGenRequestTo1Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound1To2Output() *KeyGenRound1To2Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound1To2Output); ok {
		return x.KeyGenRound1To2Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound2To3Output() *KeyGenRound2To3Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound2To3Output); ok {
		return x.KeyGenRound2To3Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound3To4Output() *KeyGenRound3To4Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound3To4Output); ok {
		return x.KeyGenRound3To4Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound4To5Output() *KeyGenRound4To5Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound4To5Output); ok {
		return x.KeyGenRound4To5Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound5To6Output() *KeyGenRound5To6Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound5To6Output); ok {
		return x.KeyGenRound5To6Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound6To7Output() *KeyGenRound6To7Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound6To7Output); ok {
		return x.KeyGenRound6To7Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound7To8Output() *KeyGenRound7To8Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound7To8Output); ok {
		return x.KeyGenRound7To8Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound8To9Output() *KeyGenRound8To9Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound8To9Output); ok {
		return x.KeyGenRound8To9Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound9To10Output() *KeyGenRound9To10Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound9To10Output); ok {
		return x.KeyGenRound9To10Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound10To11Output() *KeyGenRound10To11Output {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound10To11Output); ok {
		return x.KeyGenRound10To11Output
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRound11ToResponseOutput() *KeyGenRound11ToResponseOutput {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRound11ToResponseOutput); ok {
		return x.KeyGenRound11ToResponseOutput
	}
	return nil
}

type isKeygenMessage_Msg interface {
	isKeygenMessage_Msg()
}

type KeygenMessage_KeyGenRequestTo1Output struct {
	KeyGenRequestTo1Output *KeyGenRequestTo1Output `protobuf:"bytes,1,opt,name=keyGenRequestTo1Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound1To2Output struct {
	KeyGenRound1To2Output *KeyGenRound1To2Output `protobuf:"bytes,2,opt,name=keyGenRound1To2Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound2To3Output struct {
	KeyGenRound2To3Output *KeyGenRound2To3Output `protobuf:"bytes,3,opt,name=keyGenRound2To3Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound3To4Output struct {
	KeyGenRound3To4Output *KeyGenRound3To4Output `protobuf:"bytes,4,opt,name=keyGenRound3To4Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound4To5Output struct {
	KeyGenRound4To5Output *KeyGenRound4To5Output `protobuf:"bytes,5,opt,name=keyGenRound4To5Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound5To6Output struct {
	KeyGenRound5To6Output *KeyGenRound5To6Output `protobuf:"bytes,6,opt,name=keyGenRound5To6Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound6To7Output struct {
	KeyGenRound6To7Output *KeyGenRound6To7Output `protobuf:"bytes,7,opt,name=keyGenRound6To7Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound7To8Output struct {
	KeyGenRound7To8Output *KeyGenRound7To8Output `protobuf:"bytes,8,opt,name=keyGenRound7To8Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound8To9Output struct {
	KeyGenRound8To9Output *KeyGenRound8To9Output `protobuf:"bytes,9,opt,name=keyGenRound8To9Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound9To10Output struct {
	KeyGenRound9To10Output *KeyGenRound9To10Output `protobuf:"bytes,10,opt,name=keyGenRound9To10Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound10To11Output struct {
	KeyGenRound10To11Output *KeyGenRound10To11Output `protobuf:"bytes,11,opt,name=keyGenRound10To11Output,proto3,oneof"`
}

type KeygenMessage_KeyGenRound11ToResponseOutput struct {
	KeyGenRound11ToResponseOutput *KeyGenRound11ToResponseOutput `protobuf:"bytes,12,opt,name=keyGenRound11ToResponseOutput,proto3,oneof"`
}

func (*KeygenMessage_KeyGenRequestTo1Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound1To2Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound2To3Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound3To4Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound4To5Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound5To6Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound6To7Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound7To8Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound8To9Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound9To10Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound10To11Output) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenRound11ToResponseOutput) isKeygenMessage_Msg() {}

// 요청 메시지 DTO
type KeyGenRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeyGenRequestMessage) Reset() {
	*x = KeyGenRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRequestMessage) ProtoMessage() {}

func (x *KeyGenRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRequestMessage.ProtoReflect.Descriptor instead.
func (*KeyGenRequestMessage) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{1}
}

// 요청 -> 라운드 1
type KeyGenRequestTo1Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeyGenRequestTo1Output) Reset() {
	*x = KeyGenRequestTo1Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRequestTo1Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRequestTo1Output) ProtoMessage() {}

func (x *KeyGenRequestTo1Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRequestTo1Output.ProtoReflect.Descriptor instead.
func (*KeyGenRequestTo1Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{2}
}

// 라운드 1 -> 라운드 2
type KeyGenRound1To2Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *KeyGenRound1To2Output) Reset() {
	*x = KeyGenRound1To2Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound1To2Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound1To2Output) ProtoMessage() {}

func (x *KeyGenRound1To2Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound1To2Output.ProtoReflect.Descriptor instead.
func (*KeyGenRound1To2Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{3}
}

func (x *KeyGenRound1To2Output) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 라운드 2 -> 라운드 3
type KeyGenRound2To3Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *KeyGenRound2To3Output) Reset() {
	*x = KeyGenRound2To3Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound2To3Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound2To3Output) ProtoMessage() {}

func (x *KeyGenRound2To3Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound2To3Output.ProtoReflect.Descriptor instead.
func (*KeyGenRound2To3Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{4}
}

func (x *KeyGenRound2To3Output) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 라운드 3 -> 라운드 4
type KeyGenRound3To4Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *KeyGenRound3To4Output) Reset() {
	*x = KeyGenRound3To4Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound3To4Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound3To4Output) ProtoMessage() {}

func (x *KeyGenRound3To4Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound3To4Output.ProtoReflect.Descriptor instead.
func (*KeyGenRound3To4Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{5}
}

func (x *KeyGenRound3To4Output) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 라운드 4 -> 라운드 5
type KeyGenRound4To5Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *KeyGenRound4To5Output) Reset() {
	*x = KeyGenRound4To5Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound4To5Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound4To5Output) ProtoMessage() {}

func (x *KeyGenRound4To5Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound4To5Output.ProtoReflect.Descriptor instead.
func (*KeyGenRound4To5Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{6}
}

func (x *KeyGenRound4To5Output) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 라운드 5 -> 라운드 6
type KeyGenRound5To6Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *KeyGenRound5To6Output) Reset() {
	*x = KeyGenRound5To6Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound5To6Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound5To6Output) ProtoMessage() {}

func (x *KeyGenRound5To6Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound5To6Output.ProtoReflect.Descriptor instead.
func (*KeyGenRound5To6Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{7}
}

func (x *KeyGenRound5To6Output) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 라운드 6 -> 라운드 7
type KeyGenRound6To7Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *KeyGenRound6To7Output) Reset() {
	*x = KeyGenRound6To7Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound6To7Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound6To7Output) ProtoMessage() {}

func (x *KeyGenRound6To7Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound6To7Output.ProtoReflect.Descriptor instead.
func (*KeyGenRound6To7Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{8}
}

func (x *KeyGenRound6To7Output) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 라운드 7 -> 라운드 8
type KeyGenRound7To8Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *KeyGenRound7To8Output) Reset() {
	*x = KeyGenRound7To8Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound7To8Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound7To8Output) ProtoMessage() {}

func (x *KeyGenRound7To8Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound7To8Output.ProtoReflect.Descriptor instead.
func (*KeyGenRound7To8Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{9}
}

func (x *KeyGenRound7To8Output) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 라운드 8 -> 라운드 9
type KeyGenRound8To9Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *KeyGenRound8To9Output) Reset() {
	*x = KeyGenRound8To9Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound8To9Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound8To9Output) ProtoMessage() {}

func (x *KeyGenRound8To9Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound8To9Output.ProtoReflect.Descriptor instead.
func (*KeyGenRound8To9Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{10}
}

func (x *KeyGenRound8To9Output) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 라운드 9 -> 라운드 10
type KeyGenRound9To10Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *KeyGenRound9To10Output) Reset() {
	*x = KeyGenRound9To10Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound9To10Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound9To10Output) ProtoMessage() {}

func (x *KeyGenRound9To10Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound9To10Output.ProtoReflect.Descriptor instead.
func (*KeyGenRound9To10Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{11}
}

func (x *KeyGenRound9To10Output) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 라운드 10 -> 라운드 11(시크릿키 공유를 위함)
type KeyGenRound10To11Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretKey []byte `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
}

func (x *KeyGenRound10To11Output) Reset() {
	*x = KeyGenRound10To11Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound10To11Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound10To11Output) ProtoMessage() {}

func (x *KeyGenRound10To11Output) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound10To11Output.ProtoReflect.Descriptor instead.
func (*KeyGenRound10To11Output) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{12}
}

func (x *KeyGenRound10To11Output) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

// 라운드 11 -> 게이트 웨이
type KeyGenRound11ToResponseOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	SecretKey []byte `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
}

func (x *KeyGenRound11ToResponseOutput) Reset() {
	*x = KeyGenRound11ToResponseOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRound11ToResponseOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRound11ToResponseOutput) ProtoMessage() {}

func (x *KeyGenRound11ToResponseOutput) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRound11ToResponseOutput.ProtoReflect.Descriptor instead.
func (*KeyGenRound11ToResponseOutput) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{13}
}

func (x *KeyGenRound11ToResponseOutput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *KeyGenRound11ToResponseOutput) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

// 게이트 웨이 -> 응답
type KeyGenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	SecretKey []byte `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Duration  int32  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *KeyGenResponse) Reset() {
	*x = KeyGenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenResponse) ProtoMessage() {}

func (x *KeyGenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenResponse.ProtoReflect.Descriptor instead.
func (*KeyGenResponse) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{14}
}

func (x *KeyGenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KeyGenResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *KeyGenResponse) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

func (x *KeyGenResponse) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_keygen_keygen_proto protoreflect.FileDescriptor

var file_keygen_keygen_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2f, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x22, 0xce, 0x08,
	0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x58, 0x0a, 0x16, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x54, 0x6f, 0x31, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x31, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48,
	0x00, 0x52, 0x16, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x54, 0x6f, 0x31, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x55, 0x0a, 0x15, 0x6b, 0x65, 0x79,
	0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x54, 0x6f, 0x32, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65,
	0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x54, 0x6f,
	0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x15, 0x6b, 0x65, 0x79, 0x47, 0x65,
	0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x54, 0x6f, 0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x55, 0x0a, 0x15, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32,
	0x54, 0x6f, 0x33, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x32, 0x54, 0x6f, 0x33, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00,
	0x52, 0x15, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x54, 0x6f,
	0x33, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x55, 0x0a, 0x15, 0x6b, 0x65, 0x79, 0x47, 0x65,
	0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x54, 0x6f, 0x34, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e,
	0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x54, 0x6f, 0x34, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x15, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x33, 0x54, 0x6f, 0x34, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x55,
	0x0a, 0x15, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x54, 0x6f,
	0x35, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x34, 0x54, 0x6f, 0x35, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x15,
	0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x54, 0x6f, 0x35, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x55, 0x0a, 0x15, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x35, 0x54, 0x6f, 0x36, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65,
	0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x54, 0x6f, 0x36, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x15, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x35, 0x54, 0x6f, 0x36, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x55, 0x0a, 0x15,
	0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x36, 0x54, 0x6f, 0x37, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x65,
	0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x36, 0x54, 0x6f, 0x37, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x15, 0x6b, 0x65,
	0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x36, 0x54, 0x6f, 0x37, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x55, 0x0a, 0x15, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x37, 0x54, 0x6f, 0x38, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x47,
	0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x37, 0x54, 0x6f, 0x38, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x48, 0x00, 0x52, 0x15, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x37, 0x54, 0x6f, 0x38, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x55, 0x0a, 0x15, 0x6b, 0x65,
	0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x38, 0x54, 0x6f, 0x39, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x65, 0x79, 0x67,
	0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x38, 0x54,
	0x6f, 0x39, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x15, 0x6b, 0x65, 0x79, 0x47,
	0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x38, 0x54, 0x6f, 0x39, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x58, 0x0a, 0x16, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x39, 0x54, 0x6f, 0x31, 0x30, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x47, 0x65,
	0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x39, 0x54, 0x6f, 0x31, 0x30, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x48, 0x00, 0x52, 0x16, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x39, 0x54, 0x6f, 0x31, 0x30, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x5b, 0x0a, 0x17, 0x6b,
	0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x30, 0x54, 0x6f, 0x31, 0x31,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6b,
	0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x31, 0x30, 0x54, 0x6f, 0x31, 0x31, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52,
	0x17, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x30, 0x54, 0x6f,
	0x31, 0x31, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x6d, 0x0a, 0x1d, 0x6b, 0x65, 0x79, 0x47,
	0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x31, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x31, 0x31, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x1d, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x31, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x16,
	0x0a, 0x14, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x31, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x22, 0x31, 0x0a, 0x15, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31,
	0x54, 0x6f, 0x32, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x32, 0x54, 0x6f, 0x33, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x54, 0x6f, 0x34, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x4b, 0x65, 0x79,
	0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x54, 0x6f, 0x35, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x31, 0x0a, 0x15,
	0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x54, 0x6f, 0x36, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x31, 0x0a, 0x15, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x36, 0x54,
	0x6f, 0x37, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x37, 0x54, 0x6f, 0x38, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x38, 0x54, 0x6f, 0x39, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x32, 0x0a, 0x16, 0x4b, 0x65, 0x79, 0x47,
	0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x39, 0x54, 0x6f, 0x31, 0x30, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x38, 0x0a, 0x17,
	0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x30, 0x54, 0x6f, 0x31,
	0x31, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x58, 0x0a, 0x1d, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x31, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79,
	0x22, 0x7f, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x32, 0x4b, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x12, 0x15, 0x2e, 0x6b,
	0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79,
	0x67, 0x65, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x15,
	0x5a, 0x13, 0x74, 0x65, 0x63, 0x64, 0x73, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b,
	0x65, 0x79, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keygen_keygen_proto_rawDescOnce sync.Once
	file_keygen_keygen_proto_rawDescData = file_keygen_keygen_proto_rawDesc
)

func file_keygen_keygen_proto_rawDescGZIP() []byte {
	file_keygen_keygen_proto_rawDescOnce.Do(func() {
		file_keygen_keygen_proto_rawDescData = protoimpl.X.CompressGZIP(file_keygen_keygen_proto_rawDescData)
	})
	return file_keygen_keygen_proto_rawDescData
}

var file_keygen_keygen_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_keygen_keygen_proto_goTypes = []any{
	(*KeygenMessage)(nil),                 // 0: keygen.KeygenMessage
	(*KeyGenRequestMessage)(nil),          // 1: keygen.KeyGenRequestMessage
	(*KeyGenRequestTo1Output)(nil),        // 2: keygen.KeyGenRequestTo1Output
	(*KeyGenRound1To2Output)(nil),         // 3: keygen.KeyGenRound1To2Output
	(*KeyGenRound2To3Output)(nil),         // 4: keygen.KeyGenRound2To3Output
	(*KeyGenRound3To4Output)(nil),         // 5: keygen.KeyGenRound3To4Output
	(*KeyGenRound4To5Output)(nil),         // 6: keygen.KeyGenRound4To5Output
	(*KeyGenRound5To6Output)(nil),         // 7: keygen.KeyGenRound5To6Output
	(*KeyGenRound6To7Output)(nil),         // 8: keygen.KeyGenRound6To7Output
	(*KeyGenRound7To8Output)(nil),         // 9: keygen.KeyGenRound7To8Output
	(*KeyGenRound8To9Output)(nil),         // 10: keygen.KeyGenRound8To9Output
	(*KeyGenRound9To10Output)(nil),        // 11: keygen.KeyGenRound9To10Output
	(*KeyGenRound10To11Output)(nil),       // 12: keygen.KeyGenRound10To11Output
	(*KeyGenRound11ToResponseOutput)(nil), // 13: keygen.KeyGenRound11ToResponseOutput
	(*KeyGenResponse)(nil),                // 14: keygen.KeyGenResponse
}
var file_keygen_keygen_proto_depIdxs = []int32{
	2,  // 0: keygen.KeygenMessage.keyGenRequestTo1Output:type_name -> keygen.KeyGenRequestTo1Output
	3,  // 1: keygen.KeygenMessage.keyGenRound1To2Output:type_name -> keygen.KeyGenRound1To2Output
	4,  // 2: keygen.KeygenMessage.keyGenRound2To3Output:type_name -> keygen.KeyGenRound2To3Output
	5,  // 3: keygen.KeygenMessage.keyGenRound3To4Output:type_name -> keygen.KeyGenRound3To4Output
	6,  // 4: keygen.KeygenMessage.keyGenRound4To5Output:type_name -> keygen.KeyGenRound4To5Output
	7,  // 5: keygen.KeygenMessage.keyGenRound5To6Output:type_name -> keygen.KeyGenRound5To6Output
	8,  // 6: keygen.KeygenMessage.keyGenRound6To7Output:type_name -> keygen.KeyGenRound6To7Output
	9,  // 7: keygen.KeygenMessage.keyGenRound7To8Output:type_name -> keygen.KeyGenRound7To8Output
	10, // 8: keygen.KeygenMessage.keyGenRound8To9Output:type_name -> keygen.KeyGenRound8To9Output
	11, // 9: keygen.KeygenMessage.keyGenRound9To10Output:type_name -> keygen.KeyGenRound9To10Output
	12, // 10: keygen.KeygenMessage.keyGenRound10To11Output:type_name -> keygen.KeyGenRound10To11Output
	13, // 11: keygen.KeygenMessage.keyGenRound11ToResponseOutput:type_name -> keygen.KeyGenRound11ToResponseOutput
	0,  // 12: keygen.KeygenService.KeyGen:input_type -> keygen.KeygenMessage
	0,  // 13: keygen.KeygenService.KeyGen:output_type -> keygen.KeygenMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_keygen_keygen_proto_init() }
func file_keygen_keygen_proto_init() {
	if File_keygen_keygen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keygen_keygen_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*KeygenMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRequestTo1Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound1To2Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound2To3Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound3To4Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound4To5Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound5To6Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound6To7Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound7To8Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound8To9Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound9To10Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound10To11Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRound11ToResponseOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_keygen_keygen_proto_msgTypes[0].OneofWrappers = []any{
		(*KeygenMessage_KeyGenRequestTo1Output)(nil),
		(*KeygenMessage_KeyGenRound1To2Output)(nil),
		(*KeygenMessage_KeyGenRound2To3Output)(nil),
		(*KeygenMessage_KeyGenRound3To4Output)(nil),
		(*KeygenMessage_KeyGenRound4To5Output)(nil),
		(*KeygenMessage_KeyGenRound5To6Output)(nil),
		(*KeygenMessage_KeyGenRound6To7Output)(nil),
		(*KeygenMessage_KeyGenRound7To8Output)(nil),
		(*KeygenMessage_KeyGenRound8To9Output)(nil),
		(*KeygenMessage_KeyGenRound9To10Output)(nil),
		(*KeygenMessage_KeyGenRound10To11Output)(nil),
		(*KeygenMessage_KeyGenRound11ToResponseOutput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keygen_keygen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keygen_keygen_proto_goTypes,
		DependencyIndexes: file_keygen_keygen_proto_depIdxs,
		MessageInfos:      file_keygen_keygen_proto_msgTypes,
	}.Build()
	File_keygen_keygen_proto = out.File
	file_keygen_keygen_proto_rawDesc = nil
	file_keygen_keygen_proto_goTypes = nil
	file_keygen_keygen_proto_depIdxs = nil
}
