// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: keygen/keygen.proto

package keygen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeygenMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*KeygenMessage_KeyGenRequest
	//	*KeygenMessage_Round1Request
	//	*KeygenMessage_Round1Response
	//	*KeygenMessage_Round2Request
	//	*KeygenMessage_Round2Response
	//	*KeygenMessage_Round3Request
	//	*KeygenMessage_Round3Response
	//	*KeygenMessage_Round4Request
	//	*KeygenMessage_Round4Response
	//	*KeygenMessage_Round5Request
	//	*KeygenMessage_Round5Response
	//	*KeygenMessage_Round6Request
	//	*KeygenMessage_Round6Response
	//	*KeygenMessage_Round7Request
	//	*KeygenMessage_Round7Response
	//	*KeygenMessage_Round8Request
	//	*KeygenMessage_Round8Response
	//	*KeygenMessage_Round9Request
	//	*KeygenMessage_Round9Response
	//	*KeygenMessage_Round10Request
	//	*KeygenMessage_Round10Response
	//	*KeygenMessage_KeyGenResponse
	Msg isKeygenMessage_Msg `protobuf_oneof:"msg"`
}

func (x *KeygenMessage) Reset() {
	*x = KeygenMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeygenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenMessage) ProtoMessage() {}

func (x *KeygenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenMessage.ProtoReflect.Descriptor instead.
func (*KeygenMessage) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{0}
}

func (m *KeygenMessage) GetMsg() isKeygenMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenRequest() *KeyGenRequest {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenRequest); ok {
		return x.KeyGenRequest
	}
	return nil
}

func (x *KeygenMessage) GetRound1Request() *Round1Request {
	if x, ok := x.GetMsg().(*KeygenMessage_Round1Request); ok {
		return x.Round1Request
	}
	return nil
}

func (x *KeygenMessage) GetRound1Response() *Round1Response {
	if x, ok := x.GetMsg().(*KeygenMessage_Round1Response); ok {
		return x.Round1Response
	}
	return nil
}

func (x *KeygenMessage) GetRound2Request() *Round2Request {
	if x, ok := x.GetMsg().(*KeygenMessage_Round2Request); ok {
		return x.Round2Request
	}
	return nil
}

func (x *KeygenMessage) GetRound2Response() *Round2Response {
	if x, ok := x.GetMsg().(*KeygenMessage_Round2Response); ok {
		return x.Round2Response
	}
	return nil
}

func (x *KeygenMessage) GetRound3Request() *Round3Request {
	if x, ok := x.GetMsg().(*KeygenMessage_Round3Request); ok {
		return x.Round3Request
	}
	return nil
}

func (x *KeygenMessage) GetRound3Response() *Round3Response {
	if x, ok := x.GetMsg().(*KeygenMessage_Round3Response); ok {
		return x.Round3Response
	}
	return nil
}

func (x *KeygenMessage) GetRound4Request() *Round4Request {
	if x, ok := x.GetMsg().(*KeygenMessage_Round4Request); ok {
		return x.Round4Request
	}
	return nil
}

func (x *KeygenMessage) GetRound4Response() *Round4Response {
	if x, ok := x.GetMsg().(*KeygenMessage_Round4Response); ok {
		return x.Round4Response
	}
	return nil
}

func (x *KeygenMessage) GetRound5Request() *Round5Request {
	if x, ok := x.GetMsg().(*KeygenMessage_Round5Request); ok {
		return x.Round5Request
	}
	return nil
}

func (x *KeygenMessage) GetRound5Response() *Round5Response {
	if x, ok := x.GetMsg().(*KeygenMessage_Round5Response); ok {
		return x.Round5Response
	}
	return nil
}

func (x *KeygenMessage) GetRound6Request() *Round6Request {
	if x, ok := x.GetMsg().(*KeygenMessage_Round6Request); ok {
		return x.Round6Request
	}
	return nil
}

func (x *KeygenMessage) GetRound6Response() *Round6Response {
	if x, ok := x.GetMsg().(*KeygenMessage_Round6Response); ok {
		return x.Round6Response
	}
	return nil
}

func (x *KeygenMessage) GetRound7Request() *Round7Request {
	if x, ok := x.GetMsg().(*KeygenMessage_Round7Request); ok {
		return x.Round7Request
	}
	return nil
}

func (x *KeygenMessage) GetRound7Response() *Round7Response {
	if x, ok := x.GetMsg().(*KeygenMessage_Round7Response); ok {
		return x.Round7Response
	}
	return nil
}

func (x *KeygenMessage) GetRound8Request() *Round8Request {
	if x, ok := x.GetMsg().(*KeygenMessage_Round8Request); ok {
		return x.Round8Request
	}
	return nil
}

func (x *KeygenMessage) GetRound8Response() *Round8Response {
	if x, ok := x.GetMsg().(*KeygenMessage_Round8Response); ok {
		return x.Round8Response
	}
	return nil
}

func (x *KeygenMessage) GetRound9Request() *Round9Request {
	if x, ok := x.GetMsg().(*KeygenMessage_Round9Request); ok {
		return x.Round9Request
	}
	return nil
}

func (x *KeygenMessage) GetRound9Response() *Round9Response {
	if x, ok := x.GetMsg().(*KeygenMessage_Round9Response); ok {
		return x.Round9Response
	}
	return nil
}

func (x *KeygenMessage) GetRound10Request() *Round10Request {
	if x, ok := x.GetMsg().(*KeygenMessage_Round10Request); ok {
		return x.Round10Request
	}
	return nil
}

func (x *KeygenMessage) GetRound10Response() *Round10Response {
	if x, ok := x.GetMsg().(*KeygenMessage_Round10Response); ok {
		return x.Round10Response
	}
	return nil
}

func (x *KeygenMessage) GetKeyGenResponse() *KeyGenResponse {
	if x, ok := x.GetMsg().(*KeygenMessage_KeyGenResponse); ok {
		return x.KeyGenResponse
	}
	return nil
}

type isKeygenMessage_Msg interface {
	isKeygenMessage_Msg()
}

type KeygenMessage_KeyGenRequest struct {
	KeyGenRequest *KeyGenRequest `protobuf:"bytes,1,opt,name=keyGenRequest,proto3,oneof"`
}

type KeygenMessage_Round1Request struct {
	Round1Request *Round1Request `protobuf:"bytes,2,opt,name=round1Request,proto3,oneof"`
}

type KeygenMessage_Round1Response struct {
	Round1Response *Round1Response `protobuf:"bytes,3,opt,name=round1Response,proto3,oneof"`
}

type KeygenMessage_Round2Request struct {
	Round2Request *Round2Request `protobuf:"bytes,4,opt,name=round2Request,proto3,oneof"`
}

type KeygenMessage_Round2Response struct {
	Round2Response *Round2Response `protobuf:"bytes,5,opt,name=round2Response,proto3,oneof"`
}

type KeygenMessage_Round3Request struct {
	Round3Request *Round3Request `protobuf:"bytes,6,opt,name=round3Request,proto3,oneof"`
}

type KeygenMessage_Round3Response struct {
	Round3Response *Round3Response `protobuf:"bytes,7,opt,name=round3Response,proto3,oneof"`
}

type KeygenMessage_Round4Request struct {
	Round4Request *Round4Request `protobuf:"bytes,8,opt,name=round4Request,proto3,oneof"`
}

type KeygenMessage_Round4Response struct {
	Round4Response *Round4Response `protobuf:"bytes,9,opt,name=round4Response,proto3,oneof"`
}

type KeygenMessage_Round5Request struct {
	Round5Request *Round5Request `protobuf:"bytes,10,opt,name=round5Request,proto3,oneof"`
}

type KeygenMessage_Round5Response struct {
	Round5Response *Round5Response `protobuf:"bytes,11,opt,name=round5Response,proto3,oneof"`
}

type KeygenMessage_Round6Request struct {
	Round6Request *Round6Request `protobuf:"bytes,12,opt,name=round6Request,proto3,oneof"`
}

type KeygenMessage_Round6Response struct {
	Round6Response *Round6Response `protobuf:"bytes,13,opt,name=round6Response,proto3,oneof"`
}

type KeygenMessage_Round7Request struct {
	Round7Request *Round7Request `protobuf:"bytes,14,opt,name=round7Request,proto3,oneof"`
}

type KeygenMessage_Round7Response struct {
	Round7Response *Round7Response `protobuf:"bytes,15,opt,name=round7Response,proto3,oneof"`
}

type KeygenMessage_Round8Request struct {
	Round8Request *Round8Request `protobuf:"bytes,16,opt,name=round8Request,proto3,oneof"`
}

type KeygenMessage_Round8Response struct {
	Round8Response *Round8Response `protobuf:"bytes,17,opt,name=round8Response,proto3,oneof"`
}

type KeygenMessage_Round9Request struct {
	Round9Request *Round9Request `protobuf:"bytes,18,opt,name=round9Request,proto3,oneof"`
}

type KeygenMessage_Round9Response struct {
	Round9Response *Round9Response `protobuf:"bytes,19,opt,name=round9Response,proto3,oneof"`
}

type KeygenMessage_Round10Request struct {
	Round10Request *Round10Request `protobuf:"bytes,20,opt,name=round10Request,proto3,oneof"`
}

type KeygenMessage_Round10Response struct {
	Round10Response *Round10Response `protobuf:"bytes,21,opt,name=round10Response,proto3,oneof"`
}

type KeygenMessage_KeyGenResponse struct {
	KeyGenResponse *KeyGenResponse `protobuf:"bytes,22,opt,name=keyGenResponse,proto3,oneof"`
}

func (*KeygenMessage_KeyGenRequest) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round1Request) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round1Response) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round2Request) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round2Response) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round3Request) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round3Response) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round4Request) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round4Response) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round5Request) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round5Response) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round6Request) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round6Response) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round7Request) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round7Response) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round8Request) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round8Response) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round9Request) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round9Response) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round10Request) isKeygenMessage_Msg() {}

func (*KeygenMessage_Round10Response) isKeygenMessage_Msg() {}

func (*KeygenMessage_KeyGenResponse) isKeygenMessage_Msg() {}

type KeyGenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeyGenRequest) Reset() {
	*x = KeyGenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenRequest) ProtoMessage() {}

func (x *KeyGenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenRequest.ProtoReflect.Descriptor instead.
func (*KeyGenRequest) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{1}
}

type Round1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Round1Request) Reset() {
	*x = Round1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round1Request) ProtoMessage() {}

func (x *Round1Request) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round1Request.ProtoReflect.Descriptor instead.
func (*Round1Request) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{2}
}

type Round1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed []byte `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *Round1Response) Reset() {
	*x = Round1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round1Response) ProtoMessage() {}

func (x *Round1Response) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round1Response.ProtoReflect.Descriptor instead.
func (*Round1Response) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{3}
}

func (x *Round1Response) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type Round2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed []byte `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *Round2Request) Reset() {
	*x = Round2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round2Request) ProtoMessage() {}

func (x *Round2Request) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round2Request.ProtoReflect.Descriptor instead.
func (*Round2Request) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{4}
}

func (x *Round2Request) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type Round2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed       []byte `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Commitment []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (x *Round2Response) Reset() {
	*x = Round2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round2Response) ProtoMessage() {}

func (x *Round2Response) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round2Response.ProtoReflect.Descriptor instead.
func (*Round2Response) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{5}
}

func (x *Round2Response) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *Round2Response) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type Round3Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed       []byte `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Commitment []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (x *Round3Request) Reset() {
	*x = Round3Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round3Request) ProtoMessage() {}

func (x *Round3Request) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round3Request.ProtoReflect.Descriptor instead.
func (*Round3Request) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{6}
}

func (x *Round3Request) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *Round3Request) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type Round3Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C         []byte `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	S         []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	Statement []byte `protobuf:"bytes,3,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *Round3Response) Reset() {
	*x = Round3Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round3Response) ProtoMessage() {}

func (x *Round3Response) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round3Response.ProtoReflect.Descriptor instead.
func (*Round3Response) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{7}
}

func (x *Round3Response) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *Round3Response) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Round3Response) GetStatement() []byte {
	if x != nil {
		return x.Statement
	}
	return nil
}

type Round4Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C         []byte `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	S         []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	Statement []byte `protobuf:"bytes,3,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *Round4Request) Reset() {
	*x = Round4Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round4Request) ProtoMessage() {}

func (x *Round4Request) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round4Request.ProtoReflect.Descriptor instead.
func (*Round4Request) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{8}
}

func (x *Round4Request) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *Round4Request) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Round4Request) GetStatement() []byte {
	if x != nil {
		return x.Statement
	}
	return nil
}

type Round4Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C         []byte `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	S         []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	Statement []byte `protobuf:"bytes,3,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *Round4Response) Reset() {
	*x = Round4Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round4Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round4Response) ProtoMessage() {}

func (x *Round4Response) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round4Response.ProtoReflect.Descriptor instead.
func (*Round4Response) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{9}
}

func (x *Round4Response) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *Round4Response) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Round4Response) GetStatement() []byte {
	if x != nil {
		return x.Statement
	}
	return nil
}

type Round5Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C         []byte `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	S         []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	Statement []byte `protobuf:"bytes,3,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *Round5Request) Reset() {
	*x = Round5Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round5Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round5Request) ProtoMessage() {}

func (x *Round5Request) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round5Request.ProtoReflect.Descriptor instead.
func (*Round5Request) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{10}
}

func (x *Round5Request) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *Round5Request) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Round5Request) GetStatement() []byte {
	if x != nil {
		return x.Statement
	}
	return nil
}

type Round5Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C         []byte `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	S         []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	Statement []byte `protobuf:"bytes,3,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *Round5Response) Reset() {
	*x = Round5Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round5Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round5Response) ProtoMessage() {}

func (x *Round5Response) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round5Response.ProtoReflect.Descriptor instead.
func (*Round5Response) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{11}
}

func (x *Round5Response) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *Round5Response) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Round5Response) GetStatement() []byte {
	if x != nil {
		return x.Statement
	}
	return nil
}

type Round6Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C         []byte `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	S         []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	Statement []byte `protobuf:"bytes,3,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *Round6Request) Reset() {
	*x = Round6Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round6Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round6Request) ProtoMessage() {}

func (x *Round6Request) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round6Request.ProtoReflect.Descriptor instead.
func (*Round6Request) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{12}
}

func (x *Round6Request) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *Round6Request) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Round6Request) GetStatement() []byte {
	if x != nil {
		return x.Statement
	}
	return nil
}

type Round6Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiversMaskedChoices [][]byte `protobuf:"bytes,1,rep,name=receivers_masked_choices,json=receiversMaskedChoices,proto3" json:"receivers_masked_choices,omitempty"`
}

func (x *Round6Response) Reset() {
	*x = Round6Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round6Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round6Response) ProtoMessage() {}

func (x *Round6Response) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round6Response.ProtoReflect.Descriptor instead.
func (*Round6Response) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{13}
}

func (x *Round6Response) GetReceiversMaskedChoices() [][]byte {
	if x != nil {
		return x.ReceiversMaskedChoices
	}
	return nil
}

type Round7Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiversMaskedChoices [][]byte `protobuf:"bytes,1,rep,name=receivers_masked_choices,json=receiversMaskedChoices,proto3" json:"receivers_masked_choices,omitempty"`
}

func (x *Round7Request) Reset() {
	*x = Round7Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round7Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round7Request) ProtoMessage() {}

func (x *Round7Request) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round7Request.ProtoReflect.Descriptor instead.
func (*Round7Request) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{14}
}

func (x *Round7Request) GetReceiversMaskedChoices() [][]byte {
	if x != nil {
		return x.ReceiversMaskedChoices
	}
	return nil
}

type Round7Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtChallenges [][]byte `protobuf:"bytes,1,rep,name=ot_challenges,json=otChallenges,proto3" json:"ot_challenges,omitempty"`
}

func (x *Round7Response) Reset() {
	*x = Round7Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round7Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round7Response) ProtoMessage() {}

func (x *Round7Response) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round7Response.ProtoReflect.Descriptor instead.
func (*Round7Response) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{15}
}

func (x *Round7Response) GetOtChallenges() [][]byte {
	if x != nil {
		return x.OtChallenges
	}
	return nil
}

type Round8Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtChallenges [][]byte `protobuf:"bytes,1,rep,name=ot_challenges,json=otChallenges,proto3" json:"ot_challenges,omitempty"`
}

func (x *Round8Request) Reset() {
	*x = Round8Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round8Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round8Request) ProtoMessage() {}

func (x *Round8Request) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round8Request.ProtoReflect.Descriptor instead.
func (*Round8Request) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{16}
}

func (x *Round8Request) GetOtChallenges() [][]byte {
	if x != nil {
		return x.OtChallenges
	}
	return nil
}

type Round8Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtChallengeResponses [][]byte `protobuf:"bytes,1,rep,name=ot_challenge_responses,json=otChallengeResponses,proto3" json:"ot_challenge_responses,omitempty"`
}

func (x *Round8Response) Reset() {
	*x = Round8Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round8Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round8Response) ProtoMessage() {}

func (x *Round8Response) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round8Response.ProtoReflect.Descriptor instead.
func (*Round8Response) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{17}
}

func (x *Round8Response) GetOtChallengeResponses() [][]byte {
	if x != nil {
		return x.OtChallengeResponses
	}
	return nil
}

type Round9Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtChallengeResponses [][]byte `protobuf:"bytes,1,rep,name=ot_challenge_responses,json=otChallengeResponses,proto3" json:"ot_challenge_responses,omitempty"`
}

func (x *Round9Request) Reset() {
	*x = Round9Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round9Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round9Request) ProtoMessage() {}

func (x *Round9Request) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round9Request.ProtoReflect.Descriptor instead.
func (*Round9Request) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{18}
}

func (x *Round9Request) GetOtChallengeResponses() [][]byte {
	if x != nil {
		return x.OtChallengeResponses
	}
	return nil
}

type Round9Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChallengeOpenings [][]byte `protobuf:"bytes,1,rep,name=challenge_openings,json=challengeOpenings,proto3" json:"challenge_openings,omitempty"`
}

func (x *Round9Response) Reset() {
	*x = Round9Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round9Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round9Response) ProtoMessage() {}

func (x *Round9Response) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round9Response.ProtoReflect.Descriptor instead.
func (*Round9Response) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{19}
}

func (x *Round9Response) GetChallengeOpenings() [][]byte {
	if x != nil {
		return x.ChallengeOpenings
	}
	return nil
}

type Round10Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChallengeOpenings [][]byte `protobuf:"bytes,1,rep,name=challenge_openings,json=challengeOpenings,proto3" json:"challenge_openings,omitempty"`
}

func (x *Round10Request) Reset() {
	*x = Round10Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round10Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round10Request) ProtoMessage() {}

func (x *Round10Request) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round10Request.ProtoReflect.Descriptor instead.
func (*Round10Request) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{20}
}

func (x *Round10Request) GetChallengeOpenings() [][]byte {
	if x != nil {
		return x.ChallengeOpenings
	}
	return nil
}

type Round10Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SecretKey []byte `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
}

func (x *Round10Response) Reset() {
	*x = Round10Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Round10Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round10Response) ProtoMessage() {}

func (x *Round10Response) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round10Response.ProtoReflect.Descriptor instead.
func (*Round10Response) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{21}
}

func (x *Round10Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Round10Response) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

type KeyGenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	SecretKey []byte `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Duration  int32  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *KeyGenResponse) Reset() {
	*x = KeyGenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_keygen_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenResponse) ProtoMessage() {}

func (x *KeyGenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_keygen_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenResponse.ProtoReflect.Descriptor instead.
func (*KeyGenResponse) Descriptor() ([]byte, []int) {
	return file_keygen_keygen_proto_rawDescGZIP(), []int{22}
}

func (x *KeyGenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KeyGenResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *KeyGenResponse) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

func (x *KeyGenResponse) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_keygen_keygen_proto protoreflect.FileDescriptor

var file_keygen_keygen_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2f, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x22, 0xa7, 0x0b,
	0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x3d, 0x0a, 0x0d, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e,
	0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0d, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d,
	0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a,
	0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40,
	0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e,
	0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x40, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e,
	0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65,
	0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x40, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65,
	0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x67,
	0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x40, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b, 0x65, 0x79, 0x67,
	0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x36, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x65, 0x79,
	0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x36, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x36, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x36, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b, 0x65, 0x79,
	0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x36, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x36, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x37, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x65,
	0x79, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x37, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x37, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x37, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b, 0x65,
	0x79, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x37, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x37, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x38, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b,
	0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x38, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x38, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x38, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b,
	0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x38, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x38, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x39,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x39, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x39, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x39, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x39, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x39, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x31, 0x30, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x30,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x31, 0x30, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0f, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x31, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x15, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x31, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x31, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40,
	0x0a, 0x0e, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x16, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e,
	0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x0e, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0f, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x47, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x22,
	0x23, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x73, 0x65, 0x65, 0x64, 0x22, 0x44, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x43, 0x0a, 0x0d, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x4a, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x63, 0x12,
	0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x49, 0x0a, 0x0d, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x4a, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x34,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x01, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x49, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01,
	0x63, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x4a, 0x0a,
	0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x35, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0c, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a,
	0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x49, 0x0a, 0x0d, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x36, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x01, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x4a, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x36, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x18, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x6f, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x16, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73,
	0x22, 0x49, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x37, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x38, 0x0a, 0x18, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x5f, 0x6d,
	0x61, 0x73, 0x6b, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x16, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x4d, 0x61,
	0x73, 0x6b, 0x65, 0x64, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x0e, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x37, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x6f, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x6f, 0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x73, 0x22, 0x34, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x38, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x6f, 0x74, 0x43, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x73, 0x22, 0x46, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x38, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x6f, 0x74,
	0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x14, 0x6f, 0x74, 0x43, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73,
	0x22, 0x45, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x39, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x34, 0x0a, 0x16, 0x6f, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x14, 0x6f, 0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x39, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x11, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x3f, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x31, 0x30, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x11, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x4a, 0x0a, 0x0f, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x31, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x7f, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x4b, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x4b, 0x65, 0x79, 0x47, 0x65,
	0x6e, 0x12, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x67, 0x65,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65,
	0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x15, 0x5a, 0x13, 0x74, 0x65, 0x63, 0x64, 0x73, 0x61, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_keygen_keygen_proto_rawDescOnce sync.Once
	file_keygen_keygen_proto_rawDescData = file_keygen_keygen_proto_rawDesc
)

func file_keygen_keygen_proto_rawDescGZIP() []byte {
	file_keygen_keygen_proto_rawDescOnce.Do(func() {
		file_keygen_keygen_proto_rawDescData = protoimpl.X.CompressGZIP(file_keygen_keygen_proto_rawDescData)
	})
	return file_keygen_keygen_proto_rawDescData
}

var file_keygen_keygen_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_keygen_keygen_proto_goTypes = []any{
	(*KeygenMessage)(nil),   // 0: keygen.KeygenMessage
	(*KeyGenRequest)(nil),   // 1: keygen.KeyGenRequest
	(*Round1Request)(nil),   // 2: keygen.Round1Request
	(*Round1Response)(nil),  // 3: keygen.Round1Response
	(*Round2Request)(nil),   // 4: keygen.Round2Request
	(*Round2Response)(nil),  // 5: keygen.Round2Response
	(*Round3Request)(nil),   // 6: keygen.Round3Request
	(*Round3Response)(nil),  // 7: keygen.Round3Response
	(*Round4Request)(nil),   // 8: keygen.Round4Request
	(*Round4Response)(nil),  // 9: keygen.Round4Response
	(*Round5Request)(nil),   // 10: keygen.Round5Request
	(*Round5Response)(nil),  // 11: keygen.Round5Response
	(*Round6Request)(nil),   // 12: keygen.Round6Request
	(*Round6Response)(nil),  // 13: keygen.Round6Response
	(*Round7Request)(nil),   // 14: keygen.Round7Request
	(*Round7Response)(nil),  // 15: keygen.Round7Response
	(*Round8Request)(nil),   // 16: keygen.Round8Request
	(*Round8Response)(nil),  // 17: keygen.Round8Response
	(*Round9Request)(nil),   // 18: keygen.Round9Request
	(*Round9Response)(nil),  // 19: keygen.Round9Response
	(*Round10Request)(nil),  // 20: keygen.Round10Request
	(*Round10Response)(nil), // 21: keygen.Round10Response
	(*KeyGenResponse)(nil),  // 22: keygen.KeyGenResponse
}
var file_keygen_keygen_proto_depIdxs = []int32{
	1,  // 0: keygen.KeygenMessage.keyGenRequest:type_name -> keygen.KeyGenRequest
	2,  // 1: keygen.KeygenMessage.round1Request:type_name -> keygen.Round1Request
	3,  // 2: keygen.KeygenMessage.round1Response:type_name -> keygen.Round1Response
	4,  // 3: keygen.KeygenMessage.round2Request:type_name -> keygen.Round2Request
	5,  // 4: keygen.KeygenMessage.round2Response:type_name -> keygen.Round2Response
	6,  // 5: keygen.KeygenMessage.round3Request:type_name -> keygen.Round3Request
	7,  // 6: keygen.KeygenMessage.round3Response:type_name -> keygen.Round3Response
	8,  // 7: keygen.KeygenMessage.round4Request:type_name -> keygen.Round4Request
	9,  // 8: keygen.KeygenMessage.round4Response:type_name -> keygen.Round4Response
	10, // 9: keygen.KeygenMessage.round5Request:type_name -> keygen.Round5Request
	11, // 10: keygen.KeygenMessage.round5Response:type_name -> keygen.Round5Response
	12, // 11: keygen.KeygenMessage.round6Request:type_name -> keygen.Round6Request
	13, // 12: keygen.KeygenMessage.round6Response:type_name -> keygen.Round6Response
	14, // 13: keygen.KeygenMessage.round7Request:type_name -> keygen.Round7Request
	15, // 14: keygen.KeygenMessage.round7Response:type_name -> keygen.Round7Response
	16, // 15: keygen.KeygenMessage.round8Request:type_name -> keygen.Round8Request
	17, // 16: keygen.KeygenMessage.round8Response:type_name -> keygen.Round8Response
	18, // 17: keygen.KeygenMessage.round9Request:type_name -> keygen.Round9Request
	19, // 18: keygen.KeygenMessage.round9Response:type_name -> keygen.Round9Response
	20, // 19: keygen.KeygenMessage.round10Request:type_name -> keygen.Round10Request
	21, // 20: keygen.KeygenMessage.round10Response:type_name -> keygen.Round10Response
	22, // 21: keygen.KeygenMessage.keyGenResponse:type_name -> keygen.KeyGenResponse
	0,  // 22: keygen.KeygenService.KeyGen:input_type -> keygen.KeygenMessage
	0,  // 23: keygen.KeygenService.KeyGen:output_type -> keygen.KeygenMessage
	23, // [23:24] is the sub-list for method output_type
	22, // [22:23] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_keygen_keygen_proto_init() }
func file_keygen_keygen_proto_init() {
	if File_keygen_keygen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keygen_keygen_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*KeygenMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Round1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Round1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Round2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Round2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Round3Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Round3Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Round4Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Round4Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Round5Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*Round5Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Round6Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Round6Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Round7Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*Round7Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*Round8Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*Round8Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*Round9Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*Round9Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*Round10Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*Round10Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_keygen_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*KeyGenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_keygen_keygen_proto_msgTypes[0].OneofWrappers = []any{
		(*KeygenMessage_KeyGenRequest)(nil),
		(*KeygenMessage_Round1Request)(nil),
		(*KeygenMessage_Round1Response)(nil),
		(*KeygenMessage_Round2Request)(nil),
		(*KeygenMessage_Round2Response)(nil),
		(*KeygenMessage_Round3Request)(nil),
		(*KeygenMessage_Round3Response)(nil),
		(*KeygenMessage_Round4Request)(nil),
		(*KeygenMessage_Round4Response)(nil),
		(*KeygenMessage_Round5Request)(nil),
		(*KeygenMessage_Round5Response)(nil),
		(*KeygenMessage_Round6Request)(nil),
		(*KeygenMessage_Round6Response)(nil),
		(*KeygenMessage_Round7Request)(nil),
		(*KeygenMessage_Round7Response)(nil),
		(*KeygenMessage_Round8Request)(nil),
		(*KeygenMessage_Round8Response)(nil),
		(*KeygenMessage_Round9Request)(nil),
		(*KeygenMessage_Round9Response)(nil),
		(*KeygenMessage_Round10Request)(nil),
		(*KeygenMessage_Round10Response)(nil),
		(*KeygenMessage_KeyGenResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keygen_keygen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keygen_keygen_proto_goTypes,
		DependencyIndexes: file_keygen_keygen_proto_depIdxs,
		MessageInfos:      file_keygen_keygen_proto_msgTypes,
	}.Build()
	File_keygen_keygen_proto = out.File
	file_keygen_keygen_proto_rawDesc = nil
	file_keygen_keygen_proto_goTypes = nil
	file_keygen_keygen_proto_depIdxs = nil
}
